steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - '--destination=asia.gcr.io/$PROJECT_ID/hello-go:$REVISION_ID'
  - '--cache=true'
  - '--cache-ttl=6h'
  
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'hello-go'
  - '--image'
  - 'asia.gcr.io/$PROJECT_ID/hello-go:$REVISION_ID'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
